### ISSUE TITLE
Failing to keep the fire going doesn't do anything

### ISSUE THREAD

**Issue by kylesureline** [vcjhprogramming/2B-defenders#85]
> You need a fire or you will die. If you dont make a fire in the next 30 seconds you will get hypothermia and die

- Sometimes this message doesn't even appear despite doing nothing for a long time
- Waiting 30 seconds after this message appeared didn't do anything

**Comment by dpenguin** [comment]
the need fire command runs every 60 seconds then it takes 30 seconds for an alert that says you died with a page refresh following which restarts your progress
